using Dates
today = Dates.today()
now = Dates.now()
println("Today's date: ", today)
println("Current date and time: ", now)
println("Current year: ", Dates.format(now, "Y"))
println("Current month: ", Dates.format(now, "m"), " (", Dates.format(now, "u"), ")", " (", Dates.format(now, "U"), ")")
println("Current day: ", Dates.format(now, "d"))
println("Current hour: ", Dates.format(now, "H"), " (", Dates.format(now, "I"), ")")
println("Current minute: ", Dates.format(now, "M"))
println("Current second: ", Dates.format(now, "S"))
println("Current millisecond: ", Dates.format(now, "s"))
println("Current day of week: ", Dates.format(now, "e"), " (", Dates.format(now, "E"), ")")
println("Current AM/PM: ", Dates.format(now, "p"))