using Dates
today = Dates.today()#today's date
now = Dates.now()#current date and time
println("Today's date: ", today)
println("Current date and time: ", now)
println("Current date and time in all supported formats:")
#print current date and time in all supported formats
#format the date and time values with a specified pattern for all supported formats
println("Standard date and time formats:")
println("Current year: ", Dates.format(now, "Y"))
println("Current month: ", Dates.format(now, "m"), " (", Dates.format(now, "u"), ")", " (", Dates.format(now, "U"), ")")
println("Current day: ", Dates.format(now, "d"))
println("Current hour: ", Dates.format(now, "H"), " (", Dates.format(now, "I"), ")")
println("Current minute: ", Dates.format(now, "M"))
println("Current second: ", Dates.format(now, "S"))
println("Current millisecond: ", Dates.format(now, "s"))
println("Current day of week: ", Dates.format(now, "e"), " (", Dates.format(now, "E"), ")")
println("Current AM/PM: ", Dates.format(now, "p"))
println("Date and time methods:")
println("Current year: ", Dates.year(now))
println("Current month: ", Dates.month(now))
println("Current day: ", Dates.day(now))
println("Current hour: ", Dates.hour(now))
println("Current minute: ", Dates.minute(now))
println("Current second: ", Dates.second(now))
println("Current millisecond: ", Dates.millisecond(now))
println("Current day of week: ", Dates.dayofweek(now))
println("Current day of week name: ", Dates.dayname(now))
println("Current day of week abbr: ", Dates.dayabbr(now))
println("Current day of week of month: ", Dates.dayofweekofmonth(now))
println("Current day of month: ", Dates.dayofmonth(now))
println("Current days in month: ", Dates.daysinmonth(now))
println("Current days of week in month: ", Dates.daysofweekinmonth(now))
println("Current day of year: ", Dates.dayofyear(now))
println("Current week number: ", Dates.week(now))
println("Current month name: ", Dates.monthname(now))
println("Current month abbr: ", Dates.monthabbr(now))
println("Is current date a leap year? ", Dates.isleapyear(now))
println("Current days in year: ", Dates.daysinyear(now))
println("Current quarter of year: ", Dates.quarterofyear(now))
println("Current day of quarter: ", Dates.dayofquarter(now))
println("Current date: ", Dates.Date(now))
println("Current time: ", Dates.Time(now))
println("Current date and time: ", Dates.DateTime(now))
